apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
      - name: api-pod
        image: techchallengefiapapi:dev
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
        app: api-pod