apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
      - name: api-pod
        image: techchallengefiapapi:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: http://*:8080
  selector:
    matchLabels:
        app: api-pod