name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
  
    services:
      rabbitmq:
        image: masstransit/rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "curl -f http://localhost:15672 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      Solution_Name: FIAP.sln

    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
    
    - name: Test with the dotnet CLI
      run: dotnet test
