name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
  
    services:
      rabbitmq:
        image: masstransit/rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "curl -f http://localhost:15672 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    env:
      Solution_Name: fiap.sln
      # UnitTest_Path: FIAP-Pos-ArquiteturaDotNet\TechChallengeFIAP.UnitTests\TechChallengeFIAP.UnitTests.csproj
      # IntegrationTest_Path: FIAP-Pos-ArquiteturaDotNet\TechChallengeFIAP.IntegrationTests\TechChallengeFIAP.IntegrationTests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose-cicd.yml up -d

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the solution
    - name: Build project
      run: dotnet build
        
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
