name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
  
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: masstransit/rabbitmq
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "curl -f http://localhost:15672 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: 123456
          
    steps:
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build
    
    - name: Test with the dotnet CLI
      run: dotnet test
